---

- name: Ensure locale exists
  community.general.locale_gen:
    name: "{{ potos_locale_lang }}"
    state: present
  notify: Reconfigure locales

- name: set default locale
  ansible.builtin.lineinfile:
    dest: "/etc/default/locale"
    regexp: "^LANG="
    line: "LANG={{ potos_locale_lang }}"
    state: present
    backup: no
  notify: Reconfigure locales

- name: Install GUI language packs
  ansible.builtin.apt:
    pkg: {{ potos_locale_pkgs }}
