---

#- name: Example task to deploy a template
#  ansible.builtin.template:
#    src: 'potos.example.j2'
#    dest: '/potos.example'
#    owner: root
#    group: root
#    mode: '0755'
#
- name: DEBUG
  ansible.builtin.debug:
    msg: "message"
